name: Deploy dist
on: push
jobs:
    test: 
        runs-on: ubuntu-latest
        steps:
          - name: clone repo
            run: |
              echo "Cloning repo"
              git clone https://github.com/${{github.repository}}.git myfiles
              cd myfiles && ls
